CREATE USER C##IB IDENTIFIED BY "MySecurePass123";

GRANT CONNECT, RESOURCE TO C##IB;

ALTER USER C##IB QUOTA UNLIMITED ON USERS;

ALTER SESSION SET CURRENT_SCHEMA = C##IB;

CREATE TABLE documents (
                           id        NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           class_id  NUMBER        NOT NULL,
                           status    VARCHAR2(20)  NOT NULL
);

INSERT INTO documents (class_id, status) VALUES (1, 'NEW');
INSERT INTO documents (class_id, status) VALUES (1, 'IN_PROGRESS');
INSERT INTO documents (class_id, status) VALUES (1, 'COMPLETE');
INSERT INTO documents (class_id, status) VALUES (2, 'NEW');
INSERT INTO documents (class_id, status) VALUES (2, 'IN_PROGRESS');
INSERT INTO documents (class_id, status) VALUES (2, 'COMPLETE');
INSERT INTO documents (class_id, status) VALUES (3, 'NEW');
INSERT INTO documents (class_id, status) VALUES (3, 'IN_PROGRESS');
INSERT INTO documents (class_id, status) VALUES (3, 'COMPLETE');
INSERT INTO documents (class_id, status) VALUES (3, 'ARCHIVED');

COMMIT;

-- 7) Package specification
CREATE OR REPLACE PACKAGE FFO AS
    /**
     * Returns a cursor over documents matching the given class_id and status.
     *
     * @param p_class_id  filter by class_id
     * @param p_status    filter by status
     * @param p_cursor    OUT SYS_REFCURSOR returning the result set
     */
    PROCEDURE getDocuments(
        p_class_id IN  documents.class_id%TYPE,
        p_status   IN  documents.status%TYPE,
        p_cursor   OUT SYS_REFCURSOR
    );
END FFO;
/

-- 8) Package body
CREATE OR REPLACE PACKAGE BODY FFO AS

    PROCEDURE getDocuments(
        p_class_id IN  documents.class_id%TYPE,
        p_status   IN  documents.status%TYPE,
        p_cursor   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT id
                 , class_id
                 , status
            FROM documents
            WHERE class_id = p_class_id
              AND status   = p_status
            ORDER BY id;
    END getDocuments;

END FFO;
/

-- End of script
