#include "appctx.h"

QString appctx_t::get_doc_type(int value) {
	switch(value) {
	case   1: return tr("EKS");
	case   2: return tr("Local SWIFT");
	case   3: return tr("Local German");
	case   4: return tr("International");
	case   5: return tr("Internal");
	case   6: return tr("Free form order");
	case   7: return tr("E-cheque");
	case  10: return tr("Card renewal orders");
	case  11: return tr("Card block orders");
	case  12: return tr("Card close orders due to loss");
	case  13: return tr("Card unblock orders");
	case  14: return tr("VSAA pension plans");
	case  15: return tr("To ones own account");
	case  16: return tr("Currency exchange");
	case  17: return tr("Card open orders, existing account");
	case  18: return tr("Card open orders, new account");
	case  19: return tr("Additional card open orders");
	case  22: return tr("Deposit to Financial Instruments Account");	
	case  23: return tr("Withdrawal from PIGGY account");	
	case  24: return tr("Deposit to PIGGY account");	
	case  25: return tr("Salary internal");
	case  26: return tr("Salary local");
	case  30: return tr("Lattelekom");
	case  31: return tr("Lmt");
	case  32: return tr("Tele2");
	case  33: return tr("Baltkom Decoder");
	case  34: return tr("Latvijas Gaze");
	case  35: return tr("Latvenergo");
	case  36: return tr("IZZI");
	case  37: return tr("Baltkom Tikli");
	case  38: return tr("IZZI COM");
	case  39: return tr("LIVAS KTV");
	case  40: return tr("PROPANA GAZE");
	case  41: return tr("LIVAS NET");
	case  42: return tr("LIVAS");
	case  43: return tr("Baltkom TV");
	case  44: return tr("Zelta Zivtina");
	case  45: return tr("Real estate land");
	case  46: return tr("Real estate building");
	case  47: return tr("Riga real estate tax payment");
	case  48: return tr("Payment to pension fund");
	case  49: return tr("Administrative charges and other giro payments");
	case  50: return tr("BiFri");
	case  51: return tr("Latvenergo billing");
	case  52: return tr("ZetCom AMIGO");
	case  53: return tr("AAS PAREX DZIVIBA");
	case  54: return tr("TRIATEL (rekini)");
	case  55: return tr("TRIATEL (prieksapmaksas internets)");
	case  56: return tr("Kurzemes namu SIA");
	case  57: return tr("Vidzemes Augstskola");
	case  58: return tr("BTA AAS");
	case  59: return tr("Baltikums apdrosinasana");
	case  60: return tr("DDO Via NMC");
	case  61: return tr("DDO Rigas udens");
	case  62: return tr("DDO Lattelekom");
	case  63: return tr("DDO Tele2");
	case  64: return tr("DDO Baltkom Tikli");
	case  65: return tr("DDO Baltkom Decoder");
	case  81: return tr("DDO update");
	case  80: return tr("Deposit request");
	case  82: return tr("DDO close");
	case  83: return tr("Create fixed amount internal STO");
	case  84: return tr("Create fixed amount EKS STO");
	case  85: return tr("Create balance outward internal STO");
	case  86: return tr("Create balance outward EKS STO");
	case  87: return tr("Create balance inward STO");
	case  88: return tr("Create revolving credit STO");
	case  89: return tr("Update fixed amount STO");
	case  90: return tr("Update balance outward STO");
	case  91: return tr("Update balance inward STO");
	case  92: return tr("Update revolving credit STO");
	case  93: return tr("Close fixed amount STO");
	case  94: return tr("Close balance outward STO");
	case  95: return tr("Close balance inward STO");
	case  96: return tr("Close revolving credit STO");
	case  97: return tr("Update fixed amount internal EE STO");
	case  98: return tr("Close fixed amount EE STO");
	case 107: return tr("SMS create");
	case 108: return tr("SMS update");
	case 109: return tr("SMS close");
	case 110: return tr("Natural person questionnaire");
	case 111: return tr("Legal entity questionnaire (old)");
	case 112: return tr("Mortgage loan order");
	case 113: return tr("VSAA application");
	case 114: return tr("VSAA closure");
	case 115: return tr("Parex Group internal");
	case 116: return tr("Parex Group international");
	case 117: return tr("Tax payment EKS");
	case 118: return tr("Tax payment SWIFT");
	case 119: return tr("Resident person questionnaire");
	case 120: return tr("Noresident person questionnaire");
	case 121: return tr("Legal entity questionnaire");
	case 122: return tr("Internal Estonian");
	case 123: return tr("Local Estonian");
	case 124: return tr("Local SWIFT Estonian");
	case 125: return tr("SE DCL payment");
	case 126: return tr("SE DCL salary payment");
	case 127: return tr("AMAI EKS");
	case 128: return tr("AMAI INTERNAL");
	case 129: return tr("ERRA SIGN");
	case 130: return tr("ERRA ALTER");
	case 131: return tr("ERRA TERMINATE");
	case 132: return tr("ERRA CANCEL INVOICE");
	case 133: return tr("Quick payment");
	case 134: return tr("EKS Mobile");
	case 135: return tr("Internal Mobile");
	case 137: return tr("E-Invoice payment");
	case 139: return tr("Payment from Money request");
	case 138: return tr("Task Tool payment");
	case 200: return tr("Create fixed amount internal EE STO");
	case 201: return tr("Create fixed amount Esta STO");
	case 300: return tr("PAM free form order");
	case 301: return tr("Stock free form order");
	case 302: return tr("Margin free form order");
	case 303: return tr("Investment fund share buy/sell order");
	case 304: return tr("Stock purchase/sale");
	case 305: return tr("Bond purchase/sale");
	case 306: return tr("Option purchase/sale");
	case 307: return tr("Order for margin trading");
	case 308: return tr("INVDOC PAM CLOSE");
	case 309: return tr("INVDOC BROKER CLOSE");
	case 310: return tr("Cancel margin order");
	case 311: return tr("Confirmation of risks undertaken");
	case 314: return tr("Appropriateness Test Private");
	case 315: return tr("Appropriateness Test Legal");
	case 316: return tr("Confirmation on acceptance of risks Private");
	case 317: return tr("Confirmation on acceptance of risks Legal");
	case 318: return tr("INVDOC RECEIPT FI");
	case 319: return tr("INVDOC TRANSFER FI");
	case 320: return tr("INVDOC CORPORATE ACTION");
	case 321: return tr("INVDOC FI ACCOUNT CREATE");
	case 322: return tr("INVDOC FI ACCOUNT CREATE CORPORATE");
	case 323: return tr("Application to AS Citadele banka ordinary shares within IPO");
	case 324: return tr("INVDOC ANKETA FI PRIVATE 2018");
	case 325: return tr("INVDOC ANKETA FI LEGAL 2018");
	case 326: return tr("INVDOC APPROPRIATE WARNING");
	case 327: return tr("Order for AS Citadele banka shares purchase/sale");
	case 329: return tr("Partial transfer (Brokerage)");
	case 330: return tr("Full transfer (Brokerage)");
	case 331: return tr("Partial transfer (Asset Management)");
	case 332: return tr("Transfer without account closure (Asset Management)");
	case 333: return tr("Transfer with account closure (Asset Management)");
	case 500: return tr("Replace card orders");
	case 501: return tr("Maxi accounts");
	case 502: return tr("Savings accounts");
	case 503: return tr("Flex deposit");
	case 504: return tr("Flex deposit change currency");
	case 505: return tr("Flex deposit increase amount");
	case 506: return tr("3D saving account");
	case 507: return tr("GE MONEY ACC ACTIVATE");
	case 508: return tr("ACCOUNT CLOSE");
	case 509: return tr("Salary register");
	case 510: return tr("Application on changing the way/place of the card delivery");
	case 511: return tr("Activate card, received by post");
	case 512: return tr("CARD EXTENSIONS");
	case 513: return tr("VIP Application on changing the way/place of the card delivery");
	case 514: return tr("Enable mobile app quick functions");
	case 515: return tr("LOAN APPLICATION");
	case 516: return tr("Disable mobile app quick functions");
	case 517: return tr("Change to Savings Account+");
	case 518: return tr("Application on opening and maintenance of a Savings account+");
	case 519: return tr("Apliecinajums kreditkartes VISA sanemsanai");
	case 522: return tr("Replace AmEx to X card");
	case 523: return tr("Card replacement order");
	case 524: return tr("ATM CLAIM");
	case 526: return tr("Application for new card");
	case 527: return tr("CARD CLAIM");
	case 528: return tr("X smart programme upgrade");
	case 529: return tr("Auto loan");
	case 530: return tr("Refinancing");
	case 531: return tr("Card PIN change, Card - 000***000");
	case 532: return tr("Replace Citadele payment card with X smart");
	case 533: return tr("SMALL LOAN APPLICATION");
	case 535: case 536: return tr("Replace payment card with x card");
	case 537: return tr("Green Savings Account(Private)");
	case 538: return tr("Green Savings Account(Legal)");
	case 539: return tr("Small home loan");
	case 540: return tr("Home energy efficiency loan");
	case 700: return tr("Direct deposit (EE)");
	case 701: return tr("Private form for residents");
	case 702: return tr("Private form for non residents");
	case 703: return tr("Legal form for residents");
	case 704: return tr("Legal form for non residents");
	case 705: return tr("Privat contact information");
	case 706: return tr("Legal contact information");
	case 707: return tr("Private contact information for residents (inactive)");
	case 708: return tr("Private contact information for EE");
	case 709: return tr("Private contact information for non residents (inactive)");
	case 710: return tr("Consumer loan application");
	case 711: return tr("Home loan application");
	case 712: return tr("CARD KIT EVERY ONE");
	case 713: return tr("CARD KIT SENIOR");
	case 714: return tr("CARD KIT UNIOR");
	case 715: return tr("CARD KIT BASIC");
	case 716: return tr("CARD KIT GOLD");
	case 717: return tr("ACCOUNT OPEN MONO CURRENCY");
	case 718: return tr("ACCOUNT OPEN MULTI CURRENCY");
	case 719: return tr("CREDIT LIMIT INCREASE");
	case 720: return tr("CREATE PENSION 3 LEVEL");
	case 721: return tr("CREATE INSURANCE LIFE");
 	case 723: return tr("MobileSCAN license activation");
	case 724: return tr("Add a new device");
	//case 725: return tr("Remove device");
	case 725: return tr("Mobile services cancellation order");
	case 727: return tr("Credit rating");
	case 731: return tr("PAYMENT CANCELLATION");
	case 732: return tr("PAYMENT INVESTIGATION");
	case 734: return tr("PAYMENT SWIFT DETAILS");
	case 735: return tr("MobileSCAN license reservation");
	case 736: return tr("MobileSCAN contract changes and device activation");
	case 738: return tr("Application for Entrepreneur loan");
	case 739: return tr("Remotely activated MobileSCAN");
	case 740: return tr("Enable quick auth");
	case 742: return tr("Credit rating");
	case 744: return tr("Disable QUICK Mobile services");
	case 745: return tr("Home loan application");
	case 746: return tr("PUSH Notifications");
	case 747: case 760: return tr("Mortgage loan Guarantor application");
	case 750: return tr("Private contact information");
	case 751: return tr("Private contact information for residents (inactive)");
	case 752: return tr("Private contact information for LV non residents");
	case 753: return tr("Private contact information for EE 2018");
	case 754: return tr("Consent to receipt of notifications and offers");
	case 755: return tr("Identification document image submission");
	case 756: return tr("X Smart application");
	case 757: return tr("Private client questionnaire LT");
	case 758: return tr("Private Contact Information LT");
	case 759: return tr("Home loan application");
	case 763: return tr("Ownership and control structure information");
	case 764: return tr("IB payment automated cancellation order");
	case 765: return tr("Pension Level 3 Fund Change");
	case 766: return tr("Legal questionnaire Baltic");	
	case 767: return tr("Legal Ownership info CHANGE");	
	case 768: return tr("Legal Ownership info ACCEPT");	
	case 769: return tr("Open Acccount for Minor");
	case 770: return tr("Minor Onboarding Order (MobApp)");
	case 771: return tr("Instant credit limit change");
	case 780: return tr("Insurance policy application");
	case 781: case 782: case 783: return tr("Application for preparation of reference");
       	case 784: return tr("Application for insurance termination");
	case 785: return tr("Application for insurance prolongation");
	case 786: return tr("New payments plan application");
	case 787: return tr("Cancel payments plan");
	case 788: return tr("Change payments plan");
	case 789: return tr("Change fee account");
	case 791: return tr("CORP - Open a monocurrency settlement account");
    	case 792: return tr("CORP - Open a multicurrency settlement account");
    	case 793: return tr("Request money");
    	case 794: return tr("Submit 'Know Your Client' documents");
	case 795: return tr("Consent to personal data processing for receipt of notifications and offers");
	case 796: return tr("Piggy open order");
	case 797: return tr("Piggy edit order");
        case 798: return tr("Guaranteed compensation application");
	case 800: return tr("Riga house management");
	case 801: return tr("O!Karte");
	case 802: return tr("Skatvis SIA");
	case 803: return tr("Ventspils L kombinat");
	case 804: return tr("Ventspils Real Estate");
	case 805: return tr("SIA Kurzemes datorcentrs");
	case 806: return tr("BALTA AAS");
	case 807: return tr("Amigo (invoice)");
	case 808: return tr("Ventspils siltums SIA");
	case 809: return tr("Ventspils Real Estate Tax Payment");
	case 810: return tr("Photoradar Fine Payment");
	case 811: return tr("Vehicle Tax Payment");
	case 812: return tr("State Police Fine Payment");
	case 813: return tr("If P&C Insurance");
	case 814: return tr("Avon Cosmetics");
	case 815: return tr("Balticom (TV, Internets)");
	case 816: return tr("CLEAN R");
	case 817: return tr("Eden udens");
	case 818: return tr("G4S Latvia");
	case 819: return tr("Oriflame");
	case 820: return tr("SEESAM Apdrosinasana");
	case 821: return tr("Viasat");
	case 822: return tr("Creditreform Latvija");
	case 823: return tr("ERGO Insurance Latvijas filiale");
	case 824: return tr("DDzKSU SIA");
	case 825: return tr("DAUTKOM TV SIA");
	case 826: return tr("EuroPark");
	case 827: return tr("Jurmalas namsaimnieks");
	case 828: return tr("Rezeknes Udens");
	case 829: return tr("PAUS KONSULTS SIA");
	case 830: return tr("Compensa Vienna Insurance Group");
	case 831: return tr("Baltijas Apdrosinasanas Nams");
	case 832: return tr("Bite Latvija");
	case 833: return tr("Latio Namsaimnieks");
	case 834: return tr("Lursoft");
	case 835: return tr("Jurmalas siltums");
	case 836: return tr("Gjensidige ADB Latvijas filiale");
	case 838: return tr("Student card");
	case 839: return tr("Jurmala Real Estate");
	case 840: return tr("Kokneses fonds (The Garden of Destiny)");
	case 841: return tr("Mandatum Life Insurance");
	case 842: return tr("220.lv");
	case 843: return tr("Hausmaster");
	case 844: return tr("Fortum Jelgava");
	case 845: return tr("Kekava county Real Estate Tax Payment ");
	case 846: return tr("Mobilly");
	case 847: return tr("Jurmala city entrance fee");
	case 848: return tr("Pilsetvides serviss");
	case 849: return tr("National Health Insurance contribution");
	case 850: return tr("Citadele Leasing SIA (incl. UniCredit Leasing SIA)");
	case 851: return tr("Utility CL Insurance Broker");
	case 852: return tr("Utility CL Prefilled LV");
	case 853: return tr("Utility CL Prefilled LT");
	case 854: return tr("Utility CL Prefilled EE");
	case 855: return tr("Utility Compensa Vienna Insurance");
	case 856: return tr("Koblenz Security");
	case 857: return tr("Citadele Factoring SIA");
	case 858: return tr("Ziedot.lv");
	case 859: return tr("Altum AS");
	case 860: return tr("Rīgas Ūdens");
	case 861: return tr("Venden");
	case 862: return tr("Balticom (telephony)");
	case 863: return tr("The Children's Hospital Foundation");
	case 1000: return tr("DE DIRECT DEPOSIT");
	case 1001: return tr("American Express Membership rewards registration");
        case 1002: return tr("AMEX ORD CARD PRIVATE");
	case 1003: return tr("AMEX ORD CARD LEGAL");
	case 1004: return tr("AMEX ORD WIN WIN");
	case 1005: return tr("AMEX ORD POS TERMINAL");
	case 1006: return tr("CREDIT CARD ORDER");
	case 1007: return tr("CNK ORD CARD PRIVATE");
	case 1008: return tr("LIFE PENSION");
	case 1010: return tr("Citadele Leasing SIA");
	case 1011: return tr("OPEN LOAN ONLINE");
	case 1012: return tr("OPEN CREDIT CARD ONLINE");
	case 1013: return tr("OPEN DEBIT CARD ONLINE");
	case 1014: return tr("OPEN LEASING ONLINE");
	case 1015: return tr("OPEN HYPOTHEC ONLINE");
	case 1016: return tr("OPEN PRIMARY ACCOUNT ONLINE");
	case 1018: return tr("Credit rating request (for business customers)");
	case 1019: return tr("Micro loan application (for business customers)");
	case 1025: return tr("EE public consumer loan");
	case 1027: return tr("MobileSCAN recovery");
	case 1028: return tr("MobileSCAN recovery mismatch");
	case 1200: return tr("Instant credit limit change");
	}
	return QString::null;
}

